BlogLife/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogLife.Helpers;
using BlogLife.Models;
using PagedList;
using PagedList.Mvc;

namespace BlogLife.Controllers
{
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        [Authorize(Roles = "Admin")]
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);

            int pageSize = 5; //specifies the number of post per page
            int pageNumber = (page ?? 1);//?? null coalescing operator

            IPagedList<BlogPost> allBlogPosts = blogList.ToPagedList(pageNumber, pageSize);
            return View(allBlogPosts);
        }
        public IQueryable<BlogPost> IndexSearch(string searchStr)
        {
            IQueryable<BlogPost> result = null;
            if (searchStr != null)
            {
                result = db.BlogPosts.AsQueryable();
                result = result.Where(b => b.Title.Contains(searchStr) ||
                    b.Body.Contains(searchStr) ||
                    b.Comments.Any(c => c.Body.Contains(searchStr) ||
                        c.Author.FirstName.Contains(searchStr) ||
                        c.Author.LastName.Contains(searchStr) ||
                        c.Author.DisplayName.Contains(searchStr) ||
                        c.Author.Email.Contains(searchStr)));
            }
            else
            {
                result = db.BlogPosts.AsQueryable();
            }
            return result.OrderByDescending(b => b.Created);
        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(string slug)
        {
            if (slug == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.FirstOrDefault(b => b.Slug == slug);
            BlogPost previousPost = db.BlogPosts.OrderByDescending(b => b.Created).ToList().SkipWhile(b => b.Created != blogPost.Created).Skip(1).FirstOrDefault();
            BlogPost nextPost = db.BlogPosts.OrderBy(b => b.Created).ToList().SkipWhile(b => b.Created != blogPost.Created).Skip(1).FirstOrDefault();

            if (previousPost == null)
            {
                ViewBag.PreviousPost = "No Earlier Posts";
            }
            else
            {
                ViewBag.PreviousPost = previousPost.Title;

            }
            if (nextPost == null)
            {
                ViewBag.NextPost = "No Newer Post";
            }
            else
            {
                ViewBag.NextPost = nextPost.Title ?? "No Newer Post";
            }

            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }
        public ActionResult PreviousPost (bool prev, int id)
        {
            if (prev)
            {
                BlogPost currentPost = db.BlogPosts.Find(id);
                BlogPost previousPost = db.BlogPosts.OrderByDescending(b => b.Created).ToList().SkipWhile(b => b.Created != currentPost.Created).Skip(1).FirstOrDefault();
                if (previousPost == null)
                {
                    return RedirectToAction(currentPost.Slug, "Blog/Details");
                }
                return RedirectToAction(previousPost.Slug, "Blog/Details");
            }
            else
            {
                BlogPost currentPost = db.BlogPosts.Find(id);
                BlogPost nextPost = db.BlogPosts.OrderBy(b => b.Created).ToList().SkipWhile(b => b.Created != currentPost.Created).Skip(1).FirstOrDefault();
                if (nextPost == null)
                {
                    return RedirectToAction(currentPost.Slug, "Blog/Details");
                }
                return RedirectToAction(nextPost.Slug, "Blog/Details");

            }
        }

       
        // GET: BlogPosts/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Body,Abstract,MediaPath,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var Slug = StringUtilities.URLFriendly(blogPost.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title");
                    return View(blogPost);
                }
                if (db.BlogPosts.Any(b => b.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique");
                    return View(blogPost);
                }
                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaPath = "/Uploads/" + fileName;
                }
                blogPost.Slug = Slug;
                blogPost.Created = DateTime.Now;
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Created,Title,Slug,Body,Abstract,MediaPath,Published")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var slug = StringUtilities.URLFriendly(blogPost.Title);
                if (slug != blogPost.Slug)
                {
                    if (String.IsNullOrWhiteSpace(slug))
                {
                        ModelState.AddModelError("Title", "Invalid title");
                        return View(blogPost);
                }
                    if (db.BlogPosts.Any(b => b.Slug == slug))
                {
                         ModelState.AddModelError("Title", "The title must be unique");
                         return View(blogPost);
                }
                    if (ImageUploadValidator.IsWebFriendlyImage(image))
                    {
                        var fileName = Path.GetFileName(image.FileName);
                        var justFileName = Path.GetFileNameWithoutExtension(fileName);
                        justFileName = StringUtilities.URLFriendly(justFileName);
                        fileName = $"{justFileName}_{DateTime.Now.Ticks}{Path.GetExtension(fileName)}";
                        image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                        blogPost.MediaPath = "/Uploads/" + fileName;
                    }
                    blogPost.Slug = slug;
                }
                
                blogPost.Updated = DateTime.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BlogLife/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us">
<head>
    <title>Swaney | BlogLife</title>
    <meta charset="UTF-8">
    <meta name="description" content="TheQuest Gaming Magazine Template">
    <meta name="keywords" content="gaming, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link href="~/Images/favicon.ico" rel="shortcut icon" />

    <!-- Google font -->
    <link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i&display=swap" rel="stylesheet">

    <!-- Stylesheets -->
    <link href="~/Content/animate.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/magnific-popup.css" rel="stylesheet" />
    <link href="~/Content/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Content/slicknav.min.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    @*<link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />*@
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css%22" rel="stylesheet" />
    <!-- Main Stylesheets -->

    <link href="~/Content/style.css" rel="stylesheet" />


    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Nav section -->

    <header class="header-section">
        <a href="/Home/Index" class="site-logo">
            <img src="~/Images/bloglogo.png" style="height:80px; width:80px" />
        </a>
        <ul class="main-menu">
            <li><a href=@Url.Action("Index","Home")>Home</a></li>
            <li><a href=@Url.Action("About", "Home")>About</a></li>
            <li><a href=@Url.Action("Contact", "Home")>Contact</a></li>
            @if (User.IsInRole("Admin"))
            {
            <li><a href=@Url.Action("Index", "BlogPosts")>Blog</a></li>
            }
            
            
        </ul>
        
        <div class="login main-menu">
            @Html.Action("_LoginPartial", "Home")
        </div>

    </header>
    <!-- Nav section end -->

    @RenderBody()

    <!-- Footer section -->

    <div class="footer-section">
        <div class="container">
            <div class="row">
                <img src="~/Images/bloglogo.png" />
                <div class="col-lg-3">
                    <div class="footer-widget">
                        <div class="about-widget">
                            <p>Brandon Swaney<br />(336)460-1802<br />1482 Giles Chapel Rd.<br />Asheboro, NC 27203</p>
                        </div>
                    </div>
                </div>
                @*<div class="col-lg-2 col-sm-6">
                    <div class="footer-widget">
                        <h2 class="fw-title">Usfull Links</h2>
                        <ul>
                            <li><a href="">Games</a></li>
                            <li><a href="">Reviews</a></li>
                            <li><a href="">Characters</a></li>
                            <li><a href="">Latest news</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-6">
                    <div class="footer-widget">
                        <h2 class="fw-title">Services</h2>
                        <ul>
                            <li><a href="">About us</a></li>
                            <li><a href="">Services</a></li>
                            <li><a href="">Become a writer</a></li>
                            <li><a href="">Jobs</a></li>
                            <li><a href="">FAQ</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-sm-6">
                    <div class="footer-widget">
                        <h2 class="fw-title">Careeres</h2>
                        <ul>
                            <li><a href="">Donate</a></li>
                            <li><a href="">Services</a></li>
                            <li><a href="">Subscriptions</a></li>
                            <li><a href="">Careers</a></li>
                            <li><a href="">Our team</a></li>
                        </ul>
                    </div>
                </div>*@
                @*<div class="col-lg-3 col-sm-6">
                    <div class="footer-widget fw-latest-post">
                        <h2 class="fw-title">Usfull Links</h2>
                        <div class="latest-news-widget">
                            <div class="ln-item">
                                <div class="ln-text">
                                    <div class="ln-date">April 1, 2019</div>
                                    <h6>10 Amazing new games</h6>
                                    <div class="ln-metas">
                                        <div class="ln-meta">By Admin</div>
                                        <div class="ln-meta">in <a href="#">Games</a></div>
                                        <div class="ln-meta">3 Comments</div>
                                    </div>
                                </div>
                            </div>
                            <div class="ln-item">
                                <div class="ln-text">
                                    <div class="ln-date">April 1, 2019</div>
                                    <h6>10 Amazing new games</h6>
                                    <div class="ln-metas">
                                        <div class="ln-meta">By Admin</div>
                                        <div class="ln-meta">in <a href="#">Games</a></div>
                                        <div class="ln-meta">3 Comments</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>*@
            </div>
            <div class="copyright">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib and modified by Brandon Swaney</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
        <div class="social-links-warp">
            <div class="container">
                <div class="social-links">
                    @*<a href="#"><i class="fa fa-instagram"></i><span>instagram</span></a>*@
                    <a href="https://github.com/2ShortGaming/BlogLife" target="_blank"><i class="fa fa-github"></i><span>github</span></a>
                    <a href="https://swaney-portfolio-cf-trn.netlify.app/" target="_blank"><i class="fa fa-facebook"></i><span>portfolio</span></a>
                    @*<a href="#"><i class="fa fa-twitter"></i><span>twitter</span></a>
                    <a href="#"><i class="fa fa-youtube"></i><span>youtube</span></a>
                    <a href="#"><i class="fa fa-tumblr-square"></i><span>tumblr</span></a>*@
                </div>
            </div>
        </div>
    </div>
    <!-- Footer section end -->
    <!--====== Javascripts & Jquery ======-->

    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.slicknav.js"></script>
    <script src="~/Scripts/owl.carousel.min.js"></script>
    <script src="~/Scripts/circle-progress.min.js"></script>
    <script src="~/Scripts/jquery.magnific-popup.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    @RenderSection("Scripts", false)

</body>
</html>






@*@if (ViewContext.HttpContext.User.IsInRole("Admin"))
{
    @Html.ActionLink("Details", "Details", new { id = item.Id });
    <br />
    @Html.ActionLink("Edit", "Edit", new { id = item.Id });
    <br />
    @Html.ActionLink("Delete", "Delete", new { id = item.Id });
    <br />
}*@